#define CRLF "\r\n"

// Error Messages
#define ERR_NOTENOUGHTPARAMS(nick, command) ("461 " + (nick) + " " + command + " :Not enough parameters" + CRLF)
#define ERR_NOSUCHCHANNEL(nick, channelname) ("403 " + (nick) + " " + (channelname) + " :No such channel" + CRLF)
#define ERR_USERNOTREGISTERED(nick) ("451 " + (nick) + " :You have not registered" + CRLF)
#define ERR_INVALIDMODEPARM(client, channelname, mode, param) ("696 " + client + " #" + (channelname) + " " + (mode) + " " + param + " :Invalid mode parameter" + CRLF)
#define ERR_KEYSET(channelname) ("467 #" + (channelname) + " Channel key already set. " + CRLF)
#define ERR_NOSUCHNICK(client, nickname) ("401 " + (client) + " " + (nickname) + " :No such nick/channel" + CRLF)
#define ERR_NEEDMODEPARM(client, command) ("461 " + (client) + " " + (command) + " :Not enough parameters" + CRLF)
#define ERR_UNKNOWNMODE(client, modechar) ("472 " + (client) + " " + std::string(1, (modechar)) + " :is unknown mode char to me" + CRLF)
#define ERR_INVITEONLYCHAN(nickname, channelname) ("473 " + nickname + " #" + channelname + " :Cannot join channel, invite only (+i)" + CRLF)
#define ERR_CHANOPRIVSNEEDED(client, channelname) ("482 " + client + " #" + channelname + " :You're not channel operator" + CRLF)
#define ERR_NOTONCHANNEL(client, channelname) ("442 " + client + " #" + channelname + " :You're not on that channel" + CRLF)
#define ERR_USERONCHANNEL(client, nick, channelname) ("443 " + client + " " + nick + " #" + channelname + " :is already on channel" + CRLF)
#define ERR_CHANNELISFULL(client, channelname) ("471 " + client + " " + channelname + " :Cannot join channel, limit achieved (+l)" + CRLF)
#define ERR_TOOMANYCHANNELS(client, channelname) ("405 " + client + " " + channelname + " :You have joined too many channels" + CRLF)
#define ERR_BADCHANNELKEY(client, channelname) ("475 " + client + " " + channelname + " :Cannot join channel, wrong key (+k)" + CRLF)
#define ERR_NORECIPIENT(client) ("411 " + client + " :No recipient given" + CRLF)
#define ERR_NOTEXTTOSEND(client) ("412 " + client + " :No text to send" + CRLF)
#define ERR_TOOMANYTARGETS(client, target) ("407 " + client + " " + target + " :Too many recepients" + CRLF)
#define ERR_USERNOTINCHANNEL(client, nick, channel) ("441 " + client + " " + nick + " " + channel + " :They aren't on that channel" + CRLF)
#define ERR_UMODEUNKNOWNFLAG(client) ("501 " + client + " :Unknown MODE flag" + CRLF)
#define ERR_NOTREGISTERED(client) ("451 " + client + " :You have not registered" + CRLF)

// Responses
#define RPL_JOINMSG(hostname, channelname) (":" + (hostname) + " JOIN #" + (channelname) + CRLF)
#define RPL_NAMREPLY(nickname, channelname, clientslist) (":localhost 353 " + (nickname) + " = #" + (channelname) + " :" + (clientslist) + CRLF)
#define RPL_ENDOFNAMES(nickname, channelname) (":localhost 366 " + (nickname) + " #" + (channelname) + " :END of /NAMES list" + CRLF)
#define RPL_TOPICIS(nickname, channelname, topic) (":localhost 332 " + (nickname) + " #" + (channelname) + " :" + (topic) + CRLF)
#define RPL_CHANNELMODES(nick, channelname, modes) ("324 " + (nick) + " #" + (channelname) + " :" + (modes) + CRLF)
#define RPL_CREATIONTIME(nick, channelname, timestamp) ("329 " + (nick) + " #" + (channelname) + " :" + (timestamp) + CRLF)
#define RPL_CHANGEMODE(hostname, channelname, mode, args) (":" + hostname + " MODE #" + (channelname) + " " + (mode) + " :" + (args) + CRLF)
#define RPL_NOTOPIC(client, channelname) ("331 " + client + " #" + channelname + " :No topic is set" + CRLF)
#define RPL_TOPIC(client, channelname, topic) ("332 " + client + " #" + channelname + " :" + topic  + CRLF)
#define RPL_TOPICWHOTIME(client, channelname, nick, setat) (":localhost 333 " + client + " #" + channelname + " " + nick + " " + setat  + CRLF)